 const PERMISSIONS = {
    ADMIN : 'ADMIN',
    USER  : 'USER',
    PERMISSIONSUPDATE : 'PERMISSIONSUPDATE',
    ITEMDELETE : 'ITEMDELETE',
    ITEMUPDATE : 'ITEMUPDATE',
    ITEMCREATE : 'ITEMCREATE',
};

exports.PERMISSIONS = PERMISSIONS;