 const PERMISSIONS = {
    ADMIN : 'ADMIN',
    USER  : 'USER',
    PERMISSION_UPDATE : 'PERMISSION_UPDATE',
    ITEM_DELETE : 'ITEM_DELETE',
    ITEM_UPDATE : 'ITEM_UPDATE',
    ITEM_CREATE : 'ITEM_CREATE',
};

exports.PERMISSIONS = PERMISSIONS;