 const PERMISSIONS = {
    ADMIN : 'ADMIN',
    USER  : 'USER',
    PERMISSIONUPDATE : 'PERMISSIONUPDATE',
    ITEMDELETE : 'ITEMDELETE',
    ITEMUPDATE : 'ITEMUPDATE',
    ITEMCREATE : 'ITEMCREATE',
};

exports.PERMISSIONS = PERMISSIONS;